services:
  kong-config-generator:
    image: alpine:3.18
    container_name: kong-config-generator
    volumes:
      - ./kong-gateway:/workspace
    env_file:
      - ./kong-gateway/.env
    entrypoint:
      - sh
      - -c
      - |
        sed -e 's|\$${IAM_SERVICE_URL}|'"$$IAM_SERVICE_URL"'|g' \
            -e 's|\$${KONG_JWT_SECRET}|'"$$KONG_JWT_SECRET"'|g' \
            -e 's|\$${KONG_JWT_ALGORITHM}|'"$$KONG_JWT_ALGORITHM"'|g' \
            -e 's|\$${KONG_REDIS_HOST}|'"$$KONG_REDIS_HOST"'|g' \
            -e 's|\$${KONG_REDIS_PORT}|'"$$KONG_REDIS_PORT"'|g' \
            -e 's|\$${KONG_REDIS_DB}|'"$$KONG_REDIS_DB"'|g' \
            /workspace/kong.template.yml > /workspace/kong_temp.yml &&
        mv /workspace/kong_temp.yml /workspace/kong.yml

  kong-gateway:
    image: kong:3.7
    container_name: kong-gateway
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - ./kong-gateway/.env
    environment:
      KONG_PLUGINS: bundled,jwt-revocation,jwt-to-header
    volumes:
      - ./kong-gateway/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./kong-gateway/plugins/jwt-revocation:/usr/local/share/lua/5.1/kong/plugins/jwt-revocation
      - ./kong-gateway/plugins/jwt-to-header:/usr/local/share/lua/5.1/kong/plugins/jwt-to-header
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy
      kong-config-generator:
        condition: service_completed_successfully
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./backend
    container_name: intern_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  db:
    image: mysql:8.4
    container_name: mysql
    restart: always
    env_file:
      - ./backend/.env.docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  db_data:
  redis_data: