"""add last_login

Revision ID: 03
Revises: cff91b456881
Create Date: 2026-06-29 00:06:18.652948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, Sequence[str], None] = 'cff91b456881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id', new_column_name='user_id', existing_type=sa.Integer(), autoincrement=True, nullable=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id', new_column_name='id', existing_type=sa.Integer(), autoincrement=True, nullable=False)
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
