"""rename_create_at_and_add_ondelete_set_null_and_delete_index_target_id

Revision ID: 06
Revises: 05
Create Date: 2026-07-17 14:58:03.258304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06'
down_revision: Union[str, Sequence[str], None] = '05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'create_at', new_column_name='created_at', existing_type=sa.DateTime(timezone=True))
    op.drop_constraint('audit_logs_ibfk_1', 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_ibfk_1', 'audit_logs', 'users', ['actor_id'], ['user_id'], ondelete='SET NULL')
    op.drop_index('ix_audit_logs_target_id', table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at', new_column_name='create_at', existing_type=sa.DateTime(timezone=True))
    op.drop_constraint('audit_logs_ibfk_1', 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_ibfk_1', 'audit_logs', 'users', ['actor_id'], ['user_id'])
    op.create_index('ix_audit_logs_target_id', 'audit_logs', ['target_id'], unique=False)
    # ### end Alembic commands ###