"""seed admin user

Revision ID: cff91b456881
Revises: c35b4e0f947d
Create Date: 2026-06-24 10:13:04.994406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff91b456881'
down_revision: Union[str, Sequence[str], None] = 'c35b4e0f947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Admin1: admin1
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO users (id, name, email, password, is_admin)
        VALUES (1, 'Admin 1', 'admin1@example.com', '$2b$12$7oD29ESB64nQmuIR/U14gujOFIYqEZ06b1/p./gJraDRHjqxy8wyy', True),
                (2, 'Admin 2', 'admin2@example.com', '$2b$12$pAAUmiJBo1zCnjg.uHbHX.klpTdUtG/mkjELEC9S5j9MLisr93d8.', True)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM users WHERE id IN (1, 2)
        """
    )
    # ### end Alembic commands ###
